### ISSUE TITLE
Port Forwarding

### ISSUE THREAD

**Issue by Dystrakti0n** [RentANerdConsulting/DebianScript#47]
Wording for Port Forwarding function:

"Will you be using port forwarding to allow access to this server?" is ambiguous. 

Will you be using port forwarding to allow external access to this server, or be using this functionality internally only?

**Comment by ninjamonkey198206** [comment]
Rewrote function to ask if NAT port forwarding would be used for external internet access, or if the system would be in DMZ or local access only.
